version: '3.8'

x-app: &app
  image: hmis-warehouse:3.1
  build:
    context: .
    args:
      RUBY_VERSION: 2.7.6
      BUNDLER_VERSION: '2.2.26'
  environment: &env
    AWS_REGION: ${AWS_REGION:-us-east-1}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN}
    AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    NODE_ENV: ${NODE_ENV:-development}
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
    CHROMEDRIVER_VERSION: 79.0.3945.36
    GROVER_NO_SANDBOX: 'true'
    BUNDLE_FORCE_RUBY_PLATFORM: 'true'
  env_file: .env.local
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache_alpine:/app/tmp/cache
    - bundle_alpine:/bundle

services:
  shell:
    <<: *backend
    profiles:
      - manual
    command: /bin/bash
    entrypoint: ''
    depends_on:
      - db
      - redis

  spec:
    <<: *backend
    profiles:
      - manual
    command: /bin/bash
    entrypoint: ''
    depends_on:
      - db
      - redis
    env_file:
      - .env.local
      - .env.test

  console:
    <<: *backend
    profiles:
      - manual
    stdin_open: true
    tty: true
    command: bundle exec rails console
    depends_on:
      - db
      - redis
      - mailhog

  dj:
    <<: *backend
    command: ./bin/rake jobs:work
    entrypoint: ''
    depends_on:
      - db
      - redis

  web:
    <<: *backend
    container_name: hmis-warehouse-web
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000"
    expose:
      - 3000
    environment:
      <<: *env
      VIRTUAL_HOST: ${FQDN:-hmis-warehouse.dev.test}
      VIRTUAL_PORT: 3000
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgis/postgis:12-3.1-alpine
    container_name: hmis-warehouse-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432
    expose:
      - 5432

  redis:
    container_name: hmis-warehouse-redis
    image: redis:alpine
    volumes:
      - redis:/data
    expose:
      - 6379

  mailhog:
    image: mailhog/mailhog:latest
    environment:
      VIRTUAL_HOST: mail.${FQDN:-hmis-warehouse.dev.test}
      VIRTUAL_PORT: 8025
    expose:
      - 8025
      - 1025

  sftp:
    container_name: hmis-warehouse-sftp
    image: atmoz/sftp
    volumes:
      - ./tmp:/home/user/sftp
      - ./spec/support/sftp.conf:/etc/sftp/users.conf:ro

volumes:
  bundle_alpine:
  node_modules_alpine:
  rails_cache_alpine:
  dbdata:
  redis:

networks:
  default:
    name: nginx-proxy
