version: '3.7'

x-app: &app
  image: hmis-warehouse:3.0
  build:
    context: .
    args:
      RUBY_VERSION: 2.7.2
      BUNDLER_VERSION: 2.2.15
  environment: &env
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    RAILS_ENV: development
    NPM_CONFIG_PREFIX: /tmp
  env_file:
    - .env.local
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_tmp_alpine:/app/tmp
    - node_modules_alpine:/app/node_modules
    - bundle_alpine:/bundle

services:
  spec:
    <<: *backend
    command: /bin/bash
    entrypoint: ''
    depends_on:
      - db
      - redis
    env_file:
      - .env.local
      - .env.test
  web:
    container_name: hmis-warehouse-web
    <<: *backend
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    expose:
      - 3000
    environment:
      <<: *env
      VIRTUAL_HOST: ${FQDN:-hmis-warehouse.dev.test}
      VIRTUAL_PORT: 3000
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgis/postgis:12-2.5-alpine
    container_name: hmis-warehouse-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:alpine
    container_name: hmis-warehouse-redis
    volumes:
      - redis:/data
    expose:
      - 6379

  mailhog:
    image: mailhog/mailhog:latest
    container_name: hmis-warehouse-mailhog
    restart: always
    environment:
      VIRTUAL_HOST: mail.${FQDN:-hmis-warehouse.dev.test}
      VIRTUAL_PORT: 8025
    expose:
      - 8025
      - 1025

volumes:
  bundle_alpine:
  node_modules_alpine:
  rails_tmp_alpine:
  dbdata:
  redis:

networks:
  default:
    name: nginx-proxy
