development:
  adapter: redis
  url: <%= "redis://#{ENV['CACHE_HOST']}:#{ENV['CACHE_PORT']}/#{ENV['CACHE_DB']}" %>
  channel_prefix: hmis_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://#{ENV['CACHE_HOST']}:#{ENV['CACHE_PORT']}/#{ENV['CACHE_DB']}" %>
  channel_prefix: hmis_production
