default_app_db: &default_app_db
  adapter: <%= ENV['DATABASE_ADAPTER'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  <% if ENV['DATABASE_PORT'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  <% end %>
  <% if ENV['DATABASE_USER'] %>
  username: <%= ENV['DATABASE_USER'] %>
  <% end %>
  <% if ENV['DATABASE_PASS'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  <% end %>
  <% if ENV['DATABASE_HOST'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  <% end %>

default_warehouse_db: &default_warehouse_db
  adapter: <%= ENV['WAREHOUSE_DATABASE_ADAPTER'] %>
  host: <%= ENV['WAREHOUSE_DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  <% if ENV['WAREHOUSE_DATABASE_PORT'] %>
  port: <%= ENV['WAREHOUSE_DATABASE_PORT'] %>
  <% end %>
  <% if ENV['WAREHOUSE_DATABASE_USER'] %>
  username: <%= ENV['WAREHOUSE_DATABASE_USER'] %>
  <% end %>
  <% if ENV['WAREHOUSE_DATABASE_PASS'] %>
  password: <%= ENV['WAREHOUSE_DATABASE_PASS'] %>
  <% end %>
  <% if ENV['WAREHOUSE_DATABASE_HOST'] %>
  host: <%= ENV['WAREHOUSE_DATABASE_HOST'] %>
  <% end %>

default_health_db: &default_health_db
  adapter: <%= ENV['HEALTH_DATABASE_ADAPTER'] %>
  host: <%= ENV['HEALTH_DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  <% if ENV['HEALTH_DATABASE_PORT'] %>
  port: <%= ENV['HEALTH_DATABASE_PORT'] %>
  <% end %>
  <% if ENV['HEALTH_DATABASE_USER'] %>
  username: <%= ENV['HEALTH_DATABASE_USER'] %>
  <% end %>
  <% if ENV['HEALTH_DATABASE_PASS'] %>
  password: <%= ENV['HEALTH_DATABASE_PASS'] %>
  <% end %>
  <% if ENV['HEALTH_DATABASE_HOST'] %>
  host: <%= ENV['HEALTH_DATABASE_HOST'] %>
  <% end %>

default_reporting_db: &default_reporting_db
  adapter: <%= ENV['REPORTING_DATABASE_ADAPTER'] %>
  host: <%= ENV['REPORTING_DATABASE_HOST'] %>
  pool: 5
  timeout: 5000
  <% if ENV['REPORTING_DATABASE_PORT'] %>
  port: <%= ENV['REPORTING_DATABASE_PORT'] %>
  <% end %>
  <% if ENV['REPORTING_DATABASE_USER'] %>
  username: <%= ENV['REPORTING_DATABASE_USER'] %>
  <% end %>
  <% if ENV['REPORTING_DATABASE_PASS'] %>
  password: <%= ENV['REPORTING_DATABASE_PASS'] %>
  <% end %>
  <% if ENV['REPORTING_DATABASE_HOST'] %>
  host: <%= ENV['REPORTING_DATABASE_HOST'] %>
  <% end %>

<%= ENV['RAILS_ENV'] %>:
  primary:
    <<: *default_app_db
    database: <%= ENV['DATABASE_APP_DB'] %>
    <% if ENV['RAILS_ENV'] == 'production' || ENV['RAILS_ENV'] == 'staging' %>
    sslmode: <%= ENV.fetch('DATABASE_SSLMODE') { 'verify-full' } %>
    sslrootcert: /etc/ssl/certs/rds-combined-ca-bundle.pem
    <% end %>
  
  warehouse:
    <<: *default_warehouse_db
    database: <%= ENV['WAREHOUSE_DATABASE_DB'] %>

  health:
    <<: *default_health_db
    database: <%= ENV['HEALTH_DATABASE_DB'] %>

  reporting:
    <<: *default_reporting_db
    database: <%= ENV['REPORTING_DATABASE_DB'] %>

<%= ENV['RAILS_ENV'] %>_cas:
  primary:
    <<: *default_app_db
    database: <%= ENV['DATABASE_CAS_DB'] %>
    <% if ENV['RAILS_ENV'] == 'production' || ENV['RAILS_ENV'] == 'staging' %>
    sslmode: <%= ENV.fetch('DATABASE_SSLMODE') { 'verify-full' } %>
    sslrootcert: /etc/ssl/certs/rds-combined-ca-bundle.pem
    <% end %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default_app_db
    database: <%= ENV['DATABASE_APP_DB_TEST'] %>

  warehouse:
    <<: *default_warehouse_db
    database: <%= ENV['WAREHOUSE_DATABASE_DB_TEST'] %>

  health:
    <<: *default_health_db
    database: <%= ENV['HEALTH_DATABASE_DB_TEST'] %>

  reporting:
    <<: *default_reporting_db
    database: <%= ENV['REPORTING_DATABASE_DB_TEST'] %>
  