on:
  push:
    branches:
      - '*'
      - '**/*'

name: Precompile any assets that have changed and push them to S3

concurrency:
  group: ${{ github.ref }}-asset-compilation
  cancel-in-progress: true

jobs:
  compile:
    name: Compile

    runs-on: ubuntu-20.04
    container: ruby:2.7.5-alpine3.13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install gems
      run: |
        bundle config set --local without 'production staging development'
        bundle install --jobs 4 --retry 3

    - name: 'App setup'
      run: |
        cp config/secrets.yml.sample config/secrets.yml
        mkdir app/assets/stylesheets/theme/styles
        touch app/assets/stylesheets/theme/styles/_variables.scss
        cp .rspec.sample .rspec
        cp config/database.yml.ci config/database.yml

    - name: Generate checksum and compile
      run: |
        # pull down secrets from SSM here
        # bundle exec bin/compile_assets.rb qa
        # but for now, just to test the load capacity of gha a bit...
        bundle exec rake assets:clobber
        bundle exec rake assets:precompile
