on:
  push:
    branches:
      - '*'
      - '**/*'

name: Precompile any assets that have changed and push them to S3

concurrency:
  group: ${{ github.ref }}-asset-compilation
  cancel-in-progress: true

jobs:
  compile:
    name: Compile

    runs-on: ubuntu-20.04
    container: ruby:2.7.5-alpine3.13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install GNU tar (required by cache step and checksumming)
      run: |
        apk add --no-cache tar

    # According to https://www.jessesquires.com/blog/2021/08/23/caching-bundler-on-github-actions/
    # this is fragile and failure prone, but the step they recommend using instead (ruby/ruby-setup)
    # isn't supported on Alpine.
    - name: cache gems
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
          /usr/local/bundle/
        key: ${{ runner.os }}-gem-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-bundler-

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up dependencies
      env:
        DATABASE_APP_DB_TEST: boston_hmis_test
        WAREHOUSE_DATABASE_DB_TEST: warehouse_test
        HEALTH_DATABASE_DB_TEST: health_test
        DATABASE_DB_TEST: boston_cas_test
        REPORTING_DATABASE_DB_TEST: test_boston_reporting
      run: |
        apk add --no-cache \
          nodejs yarn npm \
          tzdata \
          git \
          bash \
          freetds-dev \
          icu icu-dev \
          curl libcurl curl-dev \
          imagemagick \
          libmagic file-dev file \
          build-base libxml2-dev libxslt-dev postgresql-dev \
          wkhtmltopdf libgcc libstdc++ libx11 glib libxrender libxext libintl ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family \
          chromium nss freetype freetype-dev harfbuzz ca-certificates ttf-freefont \
          lftp postgresql tmux postgis geos geos-dev \
          shared-mime-info \
          python3 py3-pip

        pip3 install awscli

        echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
        chmod 600 ~/.pgpass

        npm install
        gem install bundler --version=2.2.30

    - name: Install gems
      run: |
        bundle config set --local without 'production staging development'
        bundle install --jobs 10 --retry 3

    - name: 'App setup'
      env:
        SECRETS_FILE_SECRET_ARN: ${{ secrets.SECRETS_FILE_SECRET_ARN }}
      run: |
        cp config/database.yml.ci config/database.yml
        SECRET_ARN=$SECRETS_FILE_SECRET_ARN bundle exec bin/download_secrets.rb > config/deploy/docker/assets/secret.deploy.values.yml

    - name: Generate checksum and compile
      env:
      run: |
        DEPLOY_PROTECT_SECRETS=true bundle exec bin/compile_assets.rb qa
