name: Bundle Audit and Brakeman

on:
  push:
    branches:
      - '*'
      - '**/*'
  # NOTE: you don't need to build all PRs if you are also building all branches
  # pull_request:
  #   branches:
  #     - '*'
  #     - '**/*'
jobs:
  # Label of the container job
  rails:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-20.04

    # Docker Hub image that the job executes in
    container: ruby:2.7.2-alpine

    # Service containers to run with job
    services:
      postgres:
        image: postgis/postgis:12-3.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up dependancies
        env:
          DATABASE_APP_DB_TEST: boston_hmis_test
          WAREHOUSE_DATABASE_DB_TEST: warehouse_test
          HEALTH_DATABASE_DB_TEST: health_test
          DATABASE_DB_TEST: boston_cas_test
          REPORTING_DATABASE_DB_TEST: test_boston_reporting
        run: |
          apk add --no-cache \
            nodejs yarn npm \
            tzdata \
            git \
            bash \
            freetds-dev \
            icu icu-dev \
            curl libcurl curl-dev \
            imagemagick \
            libmagic file-dev file \
            build-base libxml2-dev libxslt-dev postgresql-dev \
            wkhtmltopdf libgcc libstdc++ libx11 glib libxrender libxext libintl ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family \
            chromium nss freetype freetype-dev harfbuzz ca-certificates ttf-freefont \
            lftp postgresql postgis geos geos-dev \
            shared-mime-info

          echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
          chmod 600 ~/.pgpass

          gem install bundler --version=2.2.15

      - run: npm install

      - name: Install gems
        run: |
          bundle config set --local without 'production staging development'
          bundle install --jobs 4 --retry 3

      #- name: Run rubocop
      #  run: |
      #    bundle exec rubocop

      - name: Run bundle-audit
        run: |
          bundle exec bundle-audit check --update --ignore CVE-2015-9284 CVE-2019-16676 CVE-2017-1002201

      - name: Run brakeman
        run: |
          bundle exec brakeman -q --ensure-latest --no-pager --except PermitAttributes,Render
