name: Rails Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
  # NOTE: you don't need to build all PRs if you are also building all branches
  # pull_request:
  #   branches:
  #     - '*'
  #     - '**/*'
jobs:
  # Label of the container job
  tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-20.04

    # Docker Hub image that the job executes in
    # $RUBY_VERSION
    container: ruby:2.7.2-alpine
    steps:
      - name: Set up dependencies
        run: |
          apk add --no-cache imagemagick
          gem install bundler

      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          bundle config set --local without 'production staging development'
          bundle install --jobs 4 --retry 3
      - name: Run busted test
        run: |
          bundle exec rspec --color --fail-fast --format d spec/models/file_spec.rb
